### ISSUE TITLE
Hey there bro

### ISSUE THREAD

**Issue by Dhiraj8780** [gorouflex/DuoXPyDiscord#1]
Bro I got a instant Ban from the server as I have a new account....
Can u just unban me....

My id is:- dhiraj006606

I also have sent you friend req...

Plz unban me from the server

**Comment by gorouflex** [comment]
> Bro I got a instant Ban from the server as I have a new account.... Can u just unban me....
> 
> My id is:- dhiraj006606
> 
> I also have sent you friend req...
> 
> Plz unban me from the server

Your Discord account isn’t meet our requirements so our bot automatically ban you

**Comment by Dhiraj8780** [comment]
Can't I just get a unban?
