### ISSUE TITLE
Why I'm again banded sir?

### ISSUE THREAD

**Issue by Dhiraj8780** [gorouflex/DuoXPyDiscord#3]
Sir;
I joined the server and everything was going alright

But then I again got the ban...
For no reason..

**Comment by gorouflex** [comment]
> Sir;
> 
> I joined the server and everything was going alright
> 
> 
> 
> But then I again got the ban...
> 
> For no reason..
> 
> 
> 
> 
> 
> 

You are related to Yasser, who is currently on our blacklist, so our mod has banned you. There is no appeal. Thank you."
