### ISSUE TITLE
Im not related to him sir

### ISSUE THREAD

**Issue by Dhiraj8780** [gorouflex/DuoXPyDiscord#4]
Yasser Is just randomly on my friend list of you want I can unfriend him immediately......

And I'm doing it....

I want to stay in server please 
I want to use it sir

I didn't knew he was in your blacklist....
Please can u unban me I won't do anything.....

**Comment by gorouflex** [comment]
No appeals

**Comment by Dhiraj8780** [comment]
> No appeals

But what's my mistake I don't even know him 
Just a random discord friend
